### ISSUE TITLE
Not linking to all PelePhysics directories

### ISSUE THREAD

**Issue by ldowen** [AMReX-Combustion/PeleC#140]
https://github.com/AMReX-Combustion/PeleC/blob/b98b713ef474ce8679a0a597264b2dea11f20eed/Exec/Make.PeleC#L104

It seems that the files in PelePhysics/Support/Fuego/Evaluation are used for more than just the transport stuff. For example, using Fuego Eos means it has to have access to ReactionData.H. But that directory is only referenced if the transport types are either EGLib or Simple. If we want to use `Eos_dir := Fuego` and `Transport_dir := Constant` it can't find ReactionData.H. This would probably extend to other possible combinations as well. Are we supposed to be required to use the `Simple` or `EGLib` transport types for the Fuego EOS?

**Comment by EnnaDelfen** [comment]
Hey

Could you provide us with a failing example so we can try it out and see what the problem might be ? It's a little difficult from your post alone ! Maybe using one of the regression testings and tweaking the input file ?

Thanks

**Comment by ldowen** [comment]
Sure. If you go into the Exec/RegTests/PMF/GNUMakefile and change it so that `Transport_dir := Constant`. When you run make, it will say it can't find ReactionData.H.

**Comment by EnnaDelfen** [comment]
Hey Landon, sorry this took so long for me to look into this.
I see the problem, it's in the Make.PeleC that some locations are not included whenever the Constant Transport model is selected. It seems a bit weird that this would be the place where this header is included though, since it has to do with the chemistry directly... 
I'll propose a modif to the Makefile for PeleC people

**Comment by EnnaDelfen** [comment]
NOTE also that even though the compil does not fail anymore with the fix I'll propose, the run itself fails ! I'm pretty sure there are some bugs associated with the Constant transport model right now ...
