### ISSUE TITLE
No valid riemann solver found 

### ISSUE THREAD

**Issue by RSuryaNarayan** [AMReX-Combustion/PeleC#253]
hello, 
I am attempting a 2-d version of the `EB_BackStep `case in `Tutorials`. To do so I set `DIM=2`in the `GNUmakefile` and created a new `inputs.2d` file instead of the 3d version. Hitting `make` said `SUCCESS` but when I run the program with the `inputs.2d` file I get an error saying`Aborting, no valid riemann solver`. 
I tried adding `pelec.riemann_solver=0` (following the `_cpp_parameters`file in Source) or  `pelec.Riemann=0` as found in the PMF inputs. Observing the PMF 2-d inputs, I notice that MOL has been turned off for some reason. Has this got anything to with this (i.e/ 2-D vs 3-D case)? I tried turning off the `HYP_TYPE=MOL` in the makefile but that throws an error too.  
Any help is much appreciated. 
Thanks

**Comment by RSuryaNarayan** [comment]
Reading #125 I gather that `HYP_TYPE=PPM` is unsupported. So `HYP_TYPE=MOL` with `USE_EB=TRUE` should run. But I get the above error when I do 2-D. 3-D works just fine. Maybe something wrong with my inputs? I have just used the 3-d inputs as is but have suppressed the 3rd dimension inputs (like z-coord for EB and domain).

**Comment by jrood-nrel** [comment]
@RSuryaNarayan We have deprecated our Fortran code today and the tutorials directory, favoring the EB cases in the `Exec/RegTests` directory. In Fortran, EB was supported in 2D, but it was likely not as robust as EB in 3D. I recommend you choose an EB problem from here as a starting point https://amrex-combustion.github.io/PeleC/ebverification/ebverification.html . Also, since EB is not currently supported in 2D in PeleC, you will need to perform the problem as invariant in the third dimension and use a small blocking factor in the input file. Let us know if you need further assistance.

**Comment by RSuryaNarayan** [comment]
@jrood-nrel Thanks a lot for your reply. I indeed shrunk the z to 1 cell thick and performed a 3D (yet 2D!) analysis. So now that all the fortran kernels are deprecated, how can I update my local version? Will a `git checkout development` do the job?

**Comment by jrood-nrel** [comment]
`git pull`
