### ISSUE TITLE
Restarting a reacting simulation from an inert checkpoint file

### ISSUE THREAD

**Issue by emotheau** [AMReX-Combustion/PeleC#304]
If a checkpoint file has been generated by the code compiled with `USE_REACT = FALSE`, the code fails to restart from this checkpoint file if the code is recompiled with `USE_REACT = TRUE`.

The output throw this error:

```
restarting calculation from file: chk0000386000
Starting to call amrex_probinit ...
13 variables found in PMF file
2 data lines found in PMF file
Successfully run amrex_probinit
Successfully read inputs file ...
amrex::Error::5::operator>>(istream&,Box&): expected '(' !!!
SIGABRT
```

I suspect that when the code is compiled with `USE_REACT = TRUE`, the code is looking for Reactions_Type data that are missing in the checkpoint file. I tried to add a `state_in_checkpoint[Reactions_Type] = 0` in the routine `PeleC::set_state_in_checkpoint` in `IO.cpp` to force the reader to ignore missing data, but it is unsuccessful.

**Comment by marchdf** [comment]
This is an interesting use-case. I guess we've been talking about trying to remove some of these compile `ifdefs`. `USE_REACT` feels like a good candidate to remove because we have a duplicate runtime user parameter in `do_react` and it feels redundant to have both. One way around the issue you discuss (beyond actually fixing the code) would be to compile with `USE_REACT=TRUE` and then run with `do_react=0` and restart with `do_react=1`.
