### ISSUE TITLE
Compilation error with OpenMP

### ISSUE THREAD

**Issue by dashp7** [AMReX-Combustion/PeleC#318]
Hi,
When I try compiling the ```EB-BluffBody``` case with ```USE_OMP = TRUE```, I get the following error:
```
/home/dash/PeleC/Source/PeleC.cpp: In lambda function:
/home/dash/PeleC/Source/PeleC.cpp:2006:24: error: ‘captured_allow_small_energy’ was not declared in this scope; did you mean ‘captured_allow_negative_energy’?
 2006 |         i, j, k, sarr, captured_allow_small_energy,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        captured_allow_negative_energy
```
I am using OpenMP version 4.5
```
$ echo |cpp -fopenmp -dM |grep -i open
#define _OPENMP 201511
```
However, I am not getting such issues when I compile with ```USE_MPI = TRUE```. 

Thanks.

**Comment by jrood-nrel** [comment]
@dashp7 Thanks for reporting this. We have updated the `development` branch to compile correctly with OpenMP. Please try again.

**Comment by dashp7** [comment]
Thank you very much @jrood-nrel. Now it compiles and runs properly.

**Comment by dashp7** [comment]
Just a follow-up question regarding hybrid execution(MPI+OpenMP). Consider a case that has been compiled with MPI and OpenMP, and the executable obtained is ```PeleC2d.gnu.MPI.OMP.ex```. If I want to execute it using 2 MPI processes with 4 OpenMP threads each, is this the correct command sequence for bash?:
```
$ export OMP_NUM_THREADS=4
$ mpirun -n 2 ./PeleC2d.gnu.MPI.OMP.ex inputs_ex
```
Thanks.

**Comment by jrood-nrel** [comment]
@dashp7 Yes that should be correct in general. Certain machines with a mixture of different MPI implementations and job schedulers require different methods to this, but your example is correct for a generic cluster. When you run Pele it should report the number of threads and MPI ranks at initialization, so that can help you verify your process mapping. You can also run `top` or `htop` to verify each MPI rank is using your expected percentage of the CPU. Ranks with threads should report more than 100% usage.

**Comment by dashp7** [comment]
@jrood-nrel Thank you for the confirmation. It is working properly.

**Comment by drummerdoc** [comment]
Note that the message Jon refers to only gets printed if amrex.v=1 (which is the default). If you don't see it, check to see if your inputs file has overridden that variable.
