### ISSUE TITLE
Any further plan for supporting cylindrical coordinate system (RZ-Plane, 2D)?

### ISSUE THREAD

**Issue by yeanment** [AMReX-Combustion/PeleC#324]
We are interested in using the PeleC to conduct DNS, while the 3D simulation is pretty expensive. We notice the PeleC refuse the RZ geometric parameter. Hence, we wonder if your group have any plan for supporting cylindrical coordinate system?

**Comment by drummerdoc** [comment]
As of now, AMReX has no plans to support EB + RZ in 2D so the only possibility for RZ is when there is no embedded boundary.  Currently, we have no strong driver to support RZ without EB.

**Comment by yeanment** [comment]
Yeah, it's too pity.  We notice in a similar repo [PeleLM](https://github.com/AMReX-Combustion/PeleLM) the RZ without EB is supported. But it only applies to the zero viscosity and temperature equation is not allowed. So I wonder what's the critical problem in RZ geometry. Is the evaluation of derivative in face? But I see the derivative implementation for RZ in AMReX. If we want to implement for RZ, what do you suggest since we are not as familiar as your group.

**Comment by drummerdoc** [comment]
The metric terms have long been a part of AMReX prior to EB, so much of the data structure requirements are (or were) passed through all the right places to support RZ (and spherical in 1D).  The only real issue is properly converting EB lengths and areas into RZ...but that's someone talking before doing, so I can't possibly know the stumbling blocks ahead of time.  The real issue is that since we've moved to supporting GPU implementation, the focus has really only ever been on 3D problems (with no coordinate mappings) - the AMReX infrastructure is such that 2D problems don't often see much benefit from GPU's (too little work in the kernels). Even the ability to do Cartesian 2D was only recently added to PeleC! And frankly, there has been no serious driver applications for 2D RZ (with funding/support).  Our development has to be driven by the milestones of our funded projects and all those are currently focused on massive 3D applications.

**Comment by yeanment** [comment]
Yeah, funding is so important for the project. Actually, we only consider relatively simple geometric for now, and the EB is not so important in our simulation. Suppose this would reduce considerable amount of work. We would check the code to see which part is required for change.
