### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by RSuryaNarayan** [AMReX-Combustion/PeleC#359]
Using the latest version of PeleC. 
Tried compiling ```HIT```
```
In file included from ../../../Submodules/PelePhysics/Reactions/ReactorArkode.cpp:1:
../../../Submodules/PelePhysics/Reactions/ReactorArkode.H:5:10: fatal error: arkode/arkode_arkstep.h: No such file or directory
    5 | #include <arkode/arkode_arkstep.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [../../../Submodules/AMReX/Tools/GNUMake/Make.rules:199: tmp_build_dir/o/3d.gnu.EXE/ReactorArkode.o] Error 1
make: *** Waiting for unfinished jobs....

```

**Comment by drummerdoc** [comment]
This probably happens because in the latest versions, all the SUNDIALS integrators we support are available at runtime.  In previous versions, that was a compile-time decision, and the SUNDIALS libs were built according to the same compile-time decisions.  Try ``make TPLrealclean`` then ``make TPL``, then ``make`` again and see if this goes away.

**Comment by RSuryaNarayan** [comment]
works perfectly
