### ISSUE TITLE
prob_parm_device and prob_parm.H

### ISSUE THREAD

**Issue by SRkumar97** [AMReX-Combustion/PeleC#865]
Hi,
I have a doubt reg. the specification of flow field data/freestream conditions using the prob_parm.H and prob.cc and the *.inp files.
I am observing that in some of the testcases, say in **RegTests** folder, the freestream conditions and/or geometric parameters specified by the user in the **prob_parm.H** are cited with the prefix **"PeleC::h_prob_parm_device->"** in the prob.cpp file (**e.g. EB-BluffBody**), whereas in certain other testcases, the set of parameters specified in prob_parm.H are cited with the prefix **"prob_parm_device->"** in the corresponding prob.cpp file (**e.g. EB-ConvergingNozzle**). 

I do not understand this difference in the syntaxes of prefixes - when to use which style. Does **PeleC::** signifiy a distinct/in-built set of parameters for the prob_parm.H?

Could someone please clarify on this? Thanks in advance!

**Comment by baperry2** [comment]
Sorry about this. These data structures are definitely confusingly named. There's a bunch of gymnastics involved to appropriately copy any needed data to GPU memory for GPU-enabled simulations. I'll go into a bit more detail than is strictly necessary for your question to give a full background, but skip to the last paragraph for a simpler answer.

First, PeleC has to separate data types (structs) to store problem specific data. The first `ProbParmHost` (not used here) is a host-only structure that can contain GPU-unfriendly types like `std::string` and `amrex::Vector`. The second `ProbParmDevice` can contain only GPU-friendly data types (plain old data and pointers to data that gets explicitly allocated/copied to GPU).

The `PeleC` class has three relevant `static` members:
```
static ProbParmHost* prob_parm_host;
static ProbParmDevice* h_prob_parm_device;
static ProbParmDevice* d_prob_parm_device;
``` 

`PeleC::prob_parm_host` is basically only used as a helper to store GPU-unfriendly data when initializing the data structures. `PeleC::h_prob_parm_device` is a data structure in host memory that gets populated in `amrex_probinit` function defined in `prob.cpp`, with any dynamically sized data being allocated/copied to device as needed. `PeleC::d_prob_parm_device` is the equivalent data structure that is copy of `PeleC::h_prob_parm_device` in device memory (the copying process is handled within PeleC) and is then the data structure that actually gets passed to and used by the relevant device functions like `pc_initdata` and `bcnormal`.

Because all of these are `static` members of the `PeleC` class, they can be accessed/manipulated using the `PeleC::` prefix.

--

To answer your actual question, the `amrex_probinit` function is not a member function of the PeleC class, but can still access the `static` class members using `PeleC::`. That is why you see the members of the ProbParmDevice struct being accessed and defined with `PeleC::h_prob_parm_device->` - it means that the specific ProbParmDevice object that is a static member of PeleC is being accessed. It actually works the same way in the `EB-ConvergingNozzle` case, just in that case the separate `parse_params` function has been defined and is called from within `amrex_probinit` with `PeleC::h_prob_parm_device` as the `prob_parm_device` argument to that function. You can use whichever style you prefer. Both approaches should behave identically, it's just a matter of whether you prefer to compartmentalize the parameter parsing in a separate function.

**Comment by SRkumar97** [comment]
Thank you very much!
